export function getImageRequire(id) {
	switch (id) {
		case 1:
			return require('./assets/pokemon-assets/1.png')
		case 2:
			return require('./assets/pokemon-assets/2.png')
		case 3:
			return require('./assets/pokemon-assets/3.png')
		case 4:
			return require('./assets/pokemon-assets/4.png')
		case 5:
			return require('./assets/pokemon-assets/5.png')
		case 6:
			return require('./assets/pokemon-assets/6.png')
		case 7:
			return require('./assets/pokemon-assets/7.png')
		case 8:
			return require('./assets/pokemon-assets/8.png')
		case 9:
			return require('./assets/pokemon-assets/9.png')
		case 10:
			return require('./assets/pokemon-assets/10.png')
		case 11:
			return require('./assets/pokemon-assets/11.png')
		case 12:
			return require('./assets/pokemon-assets/12.png')
		case 13:
			return require('./assets/pokemon-assets/13.png')
		case 14:
			return require('./assets/pokemon-assets/14.png')
		case 15:
			return require('./assets/pokemon-assets/15.png')
		case 16:
			return require('./assets/pokemon-assets/16.png')
		case 17:
			return require('./assets/pokemon-assets/17.png')
		case 18:
			return require('./assets/pokemon-assets/18.png')
		case 19:
			return require('./assets/pokemon-assets/19.png')
		case 20:
			return require('./assets/pokemon-assets/20.png')
		case 21:
			return require('./assets/pokemon-assets/21.png')
		case 22:
			return require('./assets/pokemon-assets/22.png')
		case 23:
			return require('./assets/pokemon-assets/23.png')
		case 24:
			return require('./assets/pokemon-assets/24.png')
		case 25:
			return require('./assets/pokemon-assets/25.png')
		case 26:
			return require('./assets/pokemon-assets/26.png')
		case 27:
			return require('./assets/pokemon-assets/27.png')
		case 28:
			return require('./assets/pokemon-assets/28.png')
		case 29:
			return require('./assets/pokemon-assets/29.png')
		case 30:
			return require('./assets/pokemon-assets/30.png')
		case 31:
			return require('./assets/pokemon-assets/31.png')
		case 32:
			return require('./assets/pokemon-assets/32.png')
		case 33:
			return require('./assets/pokemon-assets/33.png')
		case 34:
			return require('./assets/pokemon-assets/34.png')
		case 35:
			return require('./assets/pokemon-assets/35.png')
		case 36:
			return require('./assets/pokemon-assets/36.png')
		case 37:
			return require('./assets/pokemon-assets/37.png')
		case 38:
			return require('./assets/pokemon-assets/38.png')
		case 39:
			return require('./assets/pokemon-assets/39.png')
		case 40:
			return require('./assets/pokemon-assets/40.png')
		case 41:
			return require('./assets/pokemon-assets/41.png')
		case 42:
			return require('./assets/pokemon-assets/42.png')
		case 43:
			return require('./assets/pokemon-assets/43.png')
		case 44:
			return require('./assets/pokemon-assets/44.png')
		case 45:
			return require('./assets/pokemon-assets/45.png')
		case 46:
			return require('./assets/pokemon-assets/46.png')
		case 47:
			return require('./assets/pokemon-assets/47.png')
		case 48:
			return require('./assets/pokemon-assets/48.png')
		case 49:
			return require('./assets/pokemon-assets/49.png')
		case 50:
			return require('./assets/pokemon-assets/50.png')
		case 51:
			return require('./assets/pokemon-assets/51.png')
		case 52:
			return require('./assets/pokemon-assets/52.png')
		case 53:
			return require('./assets/pokemon-assets/53.png')
		case 54:
			return require('./assets/pokemon-assets/54.png')
		case 55:
			return require('./assets/pokemon-assets/55.png')
		case 56:
			return require('./assets/pokemon-assets/56.png')
		case 57:
			return require('./assets/pokemon-assets/57.png')
		case 58:
			return require('./assets/pokemon-assets/58.png')
		case 59:
			return require('./assets/pokemon-assets/59.png')
		case 60:
			return require('./assets/pokemon-assets/60.png')
		case 61:
			return require('./assets/pokemon-assets/61.png')
		case 62:
			return require('./assets/pokemon-assets/62.png')
		case 63:
			return require('./assets/pokemon-assets/63.png')
		case 64:
			return require('./assets/pokemon-assets/64.png')
		case 65:
			return require('./assets/pokemon-assets/65.png')
		case 66:
			return require('./assets/pokemon-assets/66.png')
		case 67:
			return require('./assets/pokemon-assets/67.png')
		case 68:
			return require('./assets/pokemon-assets/68.png')
		case 69:
			return require('./assets/pokemon-assets/69.png')
		case 70:
			return require('./assets/pokemon-assets/70.png')
		case 71:
			return require('./assets/pokemon-assets/71.png')
		case 72:
			return require('./assets/pokemon-assets/72.png')
		case 73:
			return require('./assets/pokemon-assets/73.png')
		case 74:
			return require('./assets/pokemon-assets/74.png')
		case 75:
			return require('./assets/pokemon-assets/75.png')
		case 76:
			return require('./assets/pokemon-assets/76.png')
		case 77:
			return require('./assets/pokemon-assets/77.png')
		case 78:
			return require('./assets/pokemon-assets/78.png')
		case 79:
			return require('./assets/pokemon-assets/79.png')
		case 80:
			return require('./assets/pokemon-assets/80.png')
		case 81:
			return require('./assets/pokemon-assets/81.png')
		case 82:
			return require('./assets/pokemon-assets/82.png')
		case 83:
			return require('./assets/pokemon-assets/83.png')
		case 84:
			return require('./assets/pokemon-assets/84.png')
		case 85:
			return require('./assets/pokemon-assets/85.png')
		case 86:
			return require('./assets/pokemon-assets/86.png')
		case 87:
			return require('./assets/pokemon-assets/87.png')
		case 88:
			return require('./assets/pokemon-assets/88.png')
		case 89:
			return require('./assets/pokemon-assets/89.png')
		case 90:
			return require('./assets/pokemon-assets/90.png')
		case 91:
			return require('./assets/pokemon-assets/91.png')
		case 92:
			return require('./assets/pokemon-assets/92.png')
		case 93:
			return require('./assets/pokemon-assets/93.png')
		case 94:
			return require('./assets/pokemon-assets/94.png')
		case 95:
			return require('./assets/pokemon-assets/95.png')
		case 96:
			return require('./assets/pokemon-assets/96.png')
		case 97:
			return require('./assets/pokemon-assets/97.png')
		case 98:
			return require('./assets/pokemon-assets/98.png')
		case 99:
			return require('./assets/pokemon-assets/99.png')
		case 100:
			return require('./assets/pokemon-assets/100.png')
		case 101:
			return require('./assets/pokemon-assets/101.png')
		case 102:
			return require('./assets/pokemon-assets/102.png')
		case 103:
			return require('./assets/pokemon-assets/103.png')
		case 104:
			return require('./assets/pokemon-assets/104.png')
		case 105:
			return require('./assets/pokemon-assets/105.png')
		case 106:
			return require('./assets/pokemon-assets/106.png')
		case 107:
			return require('./assets/pokemon-assets/107.png')
		case 108:
			return require('./assets/pokemon-assets/108.png')
		case 109:
			return require('./assets/pokemon-assets/109.png')
		case 110:
			return require('./assets/pokemon-assets/110.png')
		case 111:
			return require('./assets/pokemon-assets/111.png')
		case 112:
			return require('./assets/pokemon-assets/112.png')
		case 113:
			return require('./assets/pokemon-assets/113.png')
		case 114:
			return require('./assets/pokemon-assets/114.png')
		case 115:
			return require('./assets/pokemon-assets/115.png')
		case 116:
			return require('./assets/pokemon-assets/116.png')
		case 117:
			return require('./assets/pokemon-assets/117.png')
		case 118:
			return require('./assets/pokemon-assets/118.png')
		case 119:
			return require('./assets/pokemon-assets/119.png')
		case 120:
			return require('./assets/pokemon-assets/120.png')
		case 121:
			return require('./assets/pokemon-assets/121.png')
		case 122:
			return require('./assets/pokemon-assets/122.png')
		case 123:
			return require('./assets/pokemon-assets/123.png')
		case 124:
			return require('./assets/pokemon-assets/124.png')
		case 125:
			return require('./assets/pokemon-assets/125.png')
		case 126:
			return require('./assets/pokemon-assets/126.png')
		case 127:
			return require('./assets/pokemon-assets/127.png')
		case 128:
			return require('./assets/pokemon-assets/128.png')
		case 129:
			return require('./assets/pokemon-assets/129.png')
		case 130:
			return require('./assets/pokemon-assets/130.png')
		case 131:
			return require('./assets/pokemon-assets/131.png')
		case 132:
			return require('./assets/pokemon-assets/132.png')
		case 133:
			return require('./assets/pokemon-assets/133.png')
		case 134:
			return require('./assets/pokemon-assets/134.png')
		case 135:
			return require('./assets/pokemon-assets/135.png')
		case 136:
			return require('./assets/pokemon-assets/136.png')
		case 137:
			return require('./assets/pokemon-assets/137.png')
		case 138:
			return require('./assets/pokemon-assets/138.png')
		case 139:
			return require('./assets/pokemon-assets/139.png')
		case 140:
			return require('./assets/pokemon-assets/140.png')
		case 141:
			return require('./assets/pokemon-assets/141.png')
		case 142:
			return require('./assets/pokemon-assets/142.png')
		case 143:
			return require('./assets/pokemon-assets/143.png')
		case 144:
			return require('./assets/pokemon-assets/144.png')
		case 145:
			return require('./assets/pokemon-assets/145.png')
		case 146:
			return require('./assets/pokemon-assets/146.png')
		case 147:
			return require('./assets/pokemon-assets/147.png')
		case 148:
			return require('./assets/pokemon-assets/148.png')
		case 149:
			return require('./assets/pokemon-assets/149.png')
		case 150:
			return require('./assets/pokemon-assets/150.png')
		case 151:
			return require('./assets/pokemon-assets/151.png')
		case 152:
			return require('./assets/pokemon-assets/152.png')
		case 153:
			return require('./assets/pokemon-assets/153.png')
		case 154:
			return require('./assets/pokemon-assets/154.png')
		case 155:
			return require('./assets/pokemon-assets/155.png')
		case 156:
			return require('./assets/pokemon-assets/156.png')
		case 157:
			return require('./assets/pokemon-assets/157.png')
		case 158:
			return require('./assets/pokemon-assets/158.png')
		case 159:
			return require('./assets/pokemon-assets/159.png')
		case 160:
			return require('./assets/pokemon-assets/160.png')
		case 161:
			return require('./assets/pokemon-assets/161.png')
		case 162:
			return require('./assets/pokemon-assets/162.png')
		case 163:
			return require('./assets/pokemon-assets/163.png')
		case 164:
			return require('./assets/pokemon-assets/164.png')
		case 165:
			return require('./assets/pokemon-assets/165.png')
		case 166:
			return require('./assets/pokemon-assets/166.png')
		case 167:
			return require('./assets/pokemon-assets/167.png')
		case 168:
			return require('./assets/pokemon-assets/168.png')
		case 169:
			return require('./assets/pokemon-assets/169.png')
		case 170:
			return require('./assets/pokemon-assets/170.png')
		case 171:
			return require('./assets/pokemon-assets/171.png')
		case 172:
			return require('./assets/pokemon-assets/172.png')
		case 173:
			return require('./assets/pokemon-assets/173.png')
		case 174:
			return require('./assets/pokemon-assets/174.png')
		case 175:
			return require('./assets/pokemon-assets/175.png')
		case 176:
			return require('./assets/pokemon-assets/176.png')
		case 177:
			return require('./assets/pokemon-assets/177.png')
		case 178:
			return require('./assets/pokemon-assets/178.png')
		case 179:
			return require('./assets/pokemon-assets/179.png')
		case 180:
			return require('./assets/pokemon-assets/180.png')
		case 181:
			return require('./assets/pokemon-assets/181.png')
		case 182:
			return require('./assets/pokemon-assets/182.png')
		case 183:
			return require('./assets/pokemon-assets/183.png')
		case 184:
			return require('./assets/pokemon-assets/184.png')
		case 185:
			return require('./assets/pokemon-assets/185.png')
		case 186:
			return require('./assets/pokemon-assets/186.png')
		case 187:
			return require('./assets/pokemon-assets/187.png')
		case 188:
			return require('./assets/pokemon-assets/188.png')
		case 189:
			return require('./assets/pokemon-assets/189.png')
		case 190:
			return require('./assets/pokemon-assets/190.png')
		case 191:
			return require('./assets/pokemon-assets/191.png')
		case 192:
			return require('./assets/pokemon-assets/192.png')
		case 193:
			return require('./assets/pokemon-assets/193.png')
		case 194:
			return require('./assets/pokemon-assets/194.png')
		case 195:
			return require('./assets/pokemon-assets/195.png')
		case 196:
			return require('./assets/pokemon-assets/196.png')
		case 197:
			return require('./assets/pokemon-assets/197.png')
		case 198:
			return require('./assets/pokemon-assets/198.png')
		case 199:
			return require('./assets/pokemon-assets/199.png')
		case 200:
			return require('./assets/pokemon-assets/200.png')
		case 201:
			return require('./assets/pokemon-assets/201.png')
		case 202:
			return require('./assets/pokemon-assets/202.png')
		case 203:
			return require('./assets/pokemon-assets/203.png')
		case 204:
			return require('./assets/pokemon-assets/204.png')
		case 205:
			return require('./assets/pokemon-assets/205.png')
		case 206:
			return require('./assets/pokemon-assets/206.png')
		case 207:
			return require('./assets/pokemon-assets/207.png')
		case 208:
			return require('./assets/pokemon-assets/208.png')
		case 209:
			return require('./assets/pokemon-assets/209.png')
		case 210:
			return require('./assets/pokemon-assets/210.png')
		case 211:
			return require('./assets/pokemon-assets/211.png')
		case 212:
			return require('./assets/pokemon-assets/212.png')
		case 213:
			return require('./assets/pokemon-assets/213.png')
		case 214:
			return require('./assets/pokemon-assets/214.png')
		case 215:
			return require('./assets/pokemon-assets/215.png')
		case 216:
			return require('./assets/pokemon-assets/216.png')
		case 217:
			return require('./assets/pokemon-assets/217.png')
		case 218:
			return require('./assets/pokemon-assets/218.png')
		case 219:
			return require('./assets/pokemon-assets/219.png')
		case 220:
			return require('./assets/pokemon-assets/220.png')
		case 221:
			return require('./assets/pokemon-assets/221.png')
		case 222:
			return require('./assets/pokemon-assets/222.png')
		case 223:
			return require('./assets/pokemon-assets/223.png')
		case 224:
			return require('./assets/pokemon-assets/224.png')
		case 225:
			return require('./assets/pokemon-assets/225.png')
		case 226:
			return require('./assets/pokemon-assets/226.png')
		case 227:
			return require('./assets/pokemon-assets/227.png')
		case 228:
			return require('./assets/pokemon-assets/228.png')
		case 229:
			return require('./assets/pokemon-assets/229.png')
		case 230:
			return require('./assets/pokemon-assets/230.png')
		case 231:
			return require('./assets/pokemon-assets/231.png')
		case 232:
			return require('./assets/pokemon-assets/232.png')
		case 233:
			return require('./assets/pokemon-assets/233.png')
		case 234:
			return require('./assets/pokemon-assets/234.png')
		case 235:
			return require('./assets/pokemon-assets/235.png')
		case 236:
			return require('./assets/pokemon-assets/236.png')
		case 237:
			return require('./assets/pokemon-assets/237.png')
		case 238:
			return require('./assets/pokemon-assets/238.png')
		case 239:
			return require('./assets/pokemon-assets/239.png')
		case 240:
			return require('./assets/pokemon-assets/240.png')
		case 241:
			return require('./assets/pokemon-assets/241.png')
		case 242:
			return require('./assets/pokemon-assets/242.png')
		case 243:
			return require('./assets/pokemon-assets/243.png')
		case 244:
			return require('./assets/pokemon-assets/244.png')
		case 245:
			return require('./assets/pokemon-assets/245.png')
		case 246:
			return require('./assets/pokemon-assets/246.png')
		case 247:
			return require('./assets/pokemon-assets/247.png')
		case 248:
			return require('./assets/pokemon-assets/248.png')
		case 249:
			return require('./assets/pokemon-assets/249.png')
		case 250:
			return require('./assets/pokemon-assets/250.png')
		case 251:
			return require('./assets/pokemon-assets/251.png')
		case 252:
			return require('./assets/pokemon-assets/252.png')
		case 253:
			return require('./assets/pokemon-assets/253.png')
		case 254:
			return require('./assets/pokemon-assets/254.png')
		case 255:
			return require('./assets/pokemon-assets/255.png')
		case 256:
			return require('./assets/pokemon-assets/256.png')
		case 257:
			return require('./assets/pokemon-assets/257.png')
		case 258:
			return require('./assets/pokemon-assets/258.png')
		case 259:
			return require('./assets/pokemon-assets/259.png')
		case 260:
			return require('./assets/pokemon-assets/260.png')
		case 261:
			return require('./assets/pokemon-assets/261.png')
		case 262:
			return require('./assets/pokemon-assets/262.png')
		case 263:
			return require('./assets/pokemon-assets/263.png')
		case 264:
			return require('./assets/pokemon-assets/264.png')
		case 265:
			return require('./assets/pokemon-assets/265.png')
		case 266:
			return require('./assets/pokemon-assets/266.png')
		case 267:
			return require('./assets/pokemon-assets/267.png')
		case 268:
			return require('./assets/pokemon-assets/268.png')
		case 269:
			return require('./assets/pokemon-assets/269.png')
		case 270:
			return require('./assets/pokemon-assets/270.png')
		case 271:
			return require('./assets/pokemon-assets/271.png')
		case 272:
			return require('./assets/pokemon-assets/272.png')
		case 273:
			return require('./assets/pokemon-assets/273.png')
		case 274:
			return require('./assets/pokemon-assets/274.png')
		case 275:
			return require('./assets/pokemon-assets/275.png')
		case 276:
			return require('./assets/pokemon-assets/276.png')
		case 277:
			return require('./assets/pokemon-assets/277.png')
		case 278:
			return require('./assets/pokemon-assets/278.png')
		case 279:
			return require('./assets/pokemon-assets/279.png')
		case 280:
			return require('./assets/pokemon-assets/280.png')
		case 281:
			return require('./assets/pokemon-assets/281.png')
		case 282:
			return require('./assets/pokemon-assets/282.png')
		case 283:
			return require('./assets/pokemon-assets/283.png')
		case 284:
			return require('./assets/pokemon-assets/284.png')
		case 285:
			return require('./assets/pokemon-assets/285.png')
		case 286:
			return require('./assets/pokemon-assets/286.png')
		case 287:
			return require('./assets/pokemon-assets/287.png')
		case 288:
			return require('./assets/pokemon-assets/288.png')
		case 289:
			return require('./assets/pokemon-assets/289.png')
		case 290:
			return require('./assets/pokemon-assets/290.png')
		case 291:
			return require('./assets/pokemon-assets/291.png')
		case 292:
			return require('./assets/pokemon-assets/292.png')
		case 293:
			return require('./assets/pokemon-assets/293.png')
		case 294:
			return require('./assets/pokemon-assets/294.png')
		case 295:
			return require('./assets/pokemon-assets/295.png')
		case 296:
			return require('./assets/pokemon-assets/296.png')
		case 297:
			return require('./assets/pokemon-assets/297.png')
		case 298:
			return require('./assets/pokemon-assets/298.png')
		case 299:
			return require('./assets/pokemon-assets/299.png')
		case 300:
			return require('./assets/pokemon-assets/300.png')
		case 301:
			return require('./assets/pokemon-assets/301.png')
		case 302:
			return require('./assets/pokemon-assets/302.png')
		case 303:
			return require('./assets/pokemon-assets/303.png')
		case 304:
			return require('./assets/pokemon-assets/304.png')
		case 305:
			return require('./assets/pokemon-assets/305.png')
		case 306:
			return require('./assets/pokemon-assets/306.png')
		case 307:
			return require('./assets/pokemon-assets/307.png')
		case 308:
			return require('./assets/pokemon-assets/308.png')
		case 309:
			return require('./assets/pokemon-assets/309.png')
		case 310:
			return require('./assets/pokemon-assets/310.png')
		case 311:
			return require('./assets/pokemon-assets/311.png')
		case 312:
			return require('./assets/pokemon-assets/312.png')
		case 313:
			return require('./assets/pokemon-assets/313.png')
		case 314:
			return require('./assets/pokemon-assets/314.png')
		case 315:
			return require('./assets/pokemon-assets/315.png')
		case 316:
			return require('./assets/pokemon-assets/316.png')
		case 317:
			return require('./assets/pokemon-assets/317.png')
		case 318:
			return require('./assets/pokemon-assets/318.png')
		case 319:
			return require('./assets/pokemon-assets/319.png')
		case 320:
			return require('./assets/pokemon-assets/320.png')
		case 321:
			return require('./assets/pokemon-assets/321.png')
		case 322:
			return require('./assets/pokemon-assets/322.png')
		case 323:
			return require('./assets/pokemon-assets/323.png')
		case 324:
			return require('./assets/pokemon-assets/324.png')
		case 325:
			return require('./assets/pokemon-assets/325.png')
		case 326:
			return require('./assets/pokemon-assets/326.png')
		case 327:
			return require('./assets/pokemon-assets/327.png')
		case 328:
			return require('./assets/pokemon-assets/328.png')
		case 329:
			return require('./assets/pokemon-assets/329.png')
		case 330:
			return require('./assets/pokemon-assets/330.png')
		case 331:
			return require('./assets/pokemon-assets/331.png')
		case 332:
			return require('./assets/pokemon-assets/332.png')
		case 333:
			return require('./assets/pokemon-assets/333.png')
		case 334:
			return require('./assets/pokemon-assets/334.png')
		case 335:
			return require('./assets/pokemon-assets/335.png')
		case 336:
			return require('./assets/pokemon-assets/336.png')
		case 337:
			return require('./assets/pokemon-assets/337.png')
		case 338:
			return require('./assets/pokemon-assets/338.png')
		case 339:
			return require('./assets/pokemon-assets/339.png')
		case 340:
			return require('./assets/pokemon-assets/340.png')
		case 341:
			return require('./assets/pokemon-assets/341.png')
		case 342:
			return require('./assets/pokemon-assets/342.png')
		case 343:
			return require('./assets/pokemon-assets/343.png')
		case 344:
			return require('./assets/pokemon-assets/344.png')
		case 345:
			return require('./assets/pokemon-assets/345.png')
		case 346:
			return require('./assets/pokemon-assets/346.png')
		case 347:
			return require('./assets/pokemon-assets/347.png')
		case 348:
			return require('./assets/pokemon-assets/348.png')
		case 349:
			return require('./assets/pokemon-assets/349.png')
		case 350:
			return require('./assets/pokemon-assets/350.png')
		case 351:
			return require('./assets/pokemon-assets/351.png')
		case 352:
			return require('./assets/pokemon-assets/352.png')
		case 353:
			return require('./assets/pokemon-assets/353.png')
		case 354:
			return require('./assets/pokemon-assets/354.png')
		case 355:
			return require('./assets/pokemon-assets/355.png')
		case 356:
			return require('./assets/pokemon-assets/356.png')
		case 357:
			return require('./assets/pokemon-assets/357.png')
		case 358:
			return require('./assets/pokemon-assets/358.png')
		case 359:
			return require('./assets/pokemon-assets/359.png')
		case 360:
			return require('./assets/pokemon-assets/360.png')
		case 361:
			return require('./assets/pokemon-assets/361.png')
		case 362:
			return require('./assets/pokemon-assets/362.png')
		case 363:
			return require('./assets/pokemon-assets/363.png')
		case 364:
			return require('./assets/pokemon-assets/364.png')
		case 365:
			return require('./assets/pokemon-assets/365.png')
		case 366:
			return require('./assets/pokemon-assets/366.png')
		case 367:
			return require('./assets/pokemon-assets/367.png')
		case 368:
			return require('./assets/pokemon-assets/368.png')
		case 369:
			return require('./assets/pokemon-assets/369.png')
		case 370:
			return require('./assets/pokemon-assets/370.png')
		case 371:
			return require('./assets/pokemon-assets/371.png')
		case 372:
			return require('./assets/pokemon-assets/372.png')
		case 373:
			return require('./assets/pokemon-assets/373.png')
		case 374:
			return require('./assets/pokemon-assets/374.png')
		case 375:
			return require('./assets/pokemon-assets/375.png')
		case 376:
			return require('./assets/pokemon-assets/376.png')
		case 377:
			return require('./assets/pokemon-assets/377.png')
		case 378:
			return require('./assets/pokemon-assets/378.png')
		case 379:
			return require('./assets/pokemon-assets/379.png')
		case 380:
			return require('./assets/pokemon-assets/380.png')
		case 381:
			return require('./assets/pokemon-assets/381.png')
		case 382:
			return require('./assets/pokemon-assets/382.png')
		case 383:
			return require('./assets/pokemon-assets/383.png')
		case 384:
			return require('./assets/pokemon-assets/384.png')
		case 385:
			return require('./assets/pokemon-assets/385.png')
		case 386:
			return require('./assets/pokemon-assets/386.png')
		case 387:
			return require('./assets/pokemon-assets/387.png')
		case 388:
			return require('./assets/pokemon-assets/388.png')
		case 389:
			return require('./assets/pokemon-assets/389.png')
		case 390:
			return require('./assets/pokemon-assets/390.png')
		case 391:
			return require('./assets/pokemon-assets/391.png')
		case 392:
			return require('./assets/pokemon-assets/392.png')
		case 393:
			return require('./assets/pokemon-assets/393.png')
		case 394:
			return require('./assets/pokemon-assets/394.png')
		case 395:
			return require('./assets/pokemon-assets/395.png')
		case 396:
			return require('./assets/pokemon-assets/396.png')
		case 397:
			return require('./assets/pokemon-assets/397.png')
		case 398:
			return require('./assets/pokemon-assets/398.png')
		case 399:
			return require('./assets/pokemon-assets/399.png')
		case 400:
			return require('./assets/pokemon-assets/400.png')
		case 401:
			return require('./assets/pokemon-assets/401.png')
		case 402:
			return require('./assets/pokemon-assets/402.png')
		case 403:
			return require('./assets/pokemon-assets/403.png')
		case 404:
			return require('./assets/pokemon-assets/404.png')
		case 405:
			return require('./assets/pokemon-assets/405.png')
		case 406:
			return require('./assets/pokemon-assets/406.png')
		case 407:
			return require('./assets/pokemon-assets/407.png')
		case 408:
			return require('./assets/pokemon-assets/408.png')
		case 409:
			return require('./assets/pokemon-assets/409.png')
		case 410:
			return require('./assets/pokemon-assets/410.png')
		case 411:
			return require('./assets/pokemon-assets/411.png')
		case 412:
			return require('./assets/pokemon-assets/412.png')
		case 413:
			return require('./assets/pokemon-assets/413.png')
		case 414:
			return require('./assets/pokemon-assets/414.png')
		case 415:
			return require('./assets/pokemon-assets/415.png')
		case 416:
			return require('./assets/pokemon-assets/416.png')
		case 417:
			return require('./assets/pokemon-assets/417.png')
		case 418:
			return require('./assets/pokemon-assets/418.png')
		case 419:
			return require('./assets/pokemon-assets/419.png')
		case 420:
			return require('./assets/pokemon-assets/420.png')
		case 421:
			return require('./assets/pokemon-assets/421.png')
		case 422:
			return require('./assets/pokemon-assets/422.png')
		case 423:
			return require('./assets/pokemon-assets/423.png')
		case 424:
			return require('./assets/pokemon-assets/424.png')
		case 425:
			return require('./assets/pokemon-assets/425.png')
		case 426:
			return require('./assets/pokemon-assets/426.png')
		case 427:
			return require('./assets/pokemon-assets/427.png')
		case 428:
			return require('./assets/pokemon-assets/428.png')
		case 429:
			return require('./assets/pokemon-assets/429.png')
		case 430:
			return require('./assets/pokemon-assets/430.png')
		case 431:
			return require('./assets/pokemon-assets/431.png')
		case 432:
			return require('./assets/pokemon-assets/432.png')
		case 433:
			return require('./assets/pokemon-assets/433.png')
		case 434:
			return require('./assets/pokemon-assets/434.png')
		case 435:
			return require('./assets/pokemon-assets/435.png')
		case 436:
			return require('./assets/pokemon-assets/436.png')
		case 437:
			return require('./assets/pokemon-assets/437.png')
		case 438:
			return require('./assets/pokemon-assets/438.png')
		case 439:
			return require('./assets/pokemon-assets/439.png')
		case 440:
			return require('./assets/pokemon-assets/440.png')
		case 441:
			return require('./assets/pokemon-assets/441.png')
		case 442:
			return require('./assets/pokemon-assets/442.png')
		case 443:
			return require('./assets/pokemon-assets/443.png')
		case 444:
			return require('./assets/pokemon-assets/444.png')
		case 445:
			return require('./assets/pokemon-assets/445.png')
		case 446:
			return require('./assets/pokemon-assets/446.png')
		case 447:
			return require('./assets/pokemon-assets/447.png')
		case 448:
			return require('./assets/pokemon-assets/448.png')
		case 449:
			return require('./assets/pokemon-assets/449.png')
		case 450:
			return require('./assets/pokemon-assets/450.png')
		case 451:
			return require('./assets/pokemon-assets/451.png')
		case 452:
			return require('./assets/pokemon-assets/452.png')
		case 453:
			return require('./assets/pokemon-assets/453.png')
		case 454:
			return require('./assets/pokemon-assets/454.png')
		case 455:
			return require('./assets/pokemon-assets/455.png')
		case 456:
			return require('./assets/pokemon-assets/456.png')
		case 457:
			return require('./assets/pokemon-assets/457.png')
		case 458:
			return require('./assets/pokemon-assets/458.png')
		case 459:
			return require('./assets/pokemon-assets/459.png')
		case 460:
			return require('./assets/pokemon-assets/460.png')
		case 461:
			return require('./assets/pokemon-assets/461.png')
		case 462:
			return require('./assets/pokemon-assets/462.png')
		case 463:
			return require('./assets/pokemon-assets/463.png')
		case 464:
			return require('./assets/pokemon-assets/464.png')
		case 465:
			return require('./assets/pokemon-assets/465.png')
		case 466:
			return require('./assets/pokemon-assets/466.png')
		case 467:
			return require('./assets/pokemon-assets/467.png')
		case 468:
			return require('./assets/pokemon-assets/468.png')
		case 469:
			return require('./assets/pokemon-assets/469.png')
		case 470:
			return require('./assets/pokemon-assets/470.png')
		case 471:
			return require('./assets/pokemon-assets/471.png')
		case 472:
			return require('./assets/pokemon-assets/472.png')
		case 473:
			return require('./assets/pokemon-assets/473.png')
		case 474:
			return require('./assets/pokemon-assets/474.png')
		case 475:
			return require('./assets/pokemon-assets/475.png')
		case 476:
			return require('./assets/pokemon-assets/476.png')
		case 477:
			return require('./assets/pokemon-assets/477.png')
		case 478:
			return require('./assets/pokemon-assets/478.png')
		case 479:
			return require('./assets/pokemon-assets/479.png')
		case 480:
			return require('./assets/pokemon-assets/480.png')
		case 481:
			return require('./assets/pokemon-assets/481.png')
		case 482:
			return require('./assets/pokemon-assets/482.png')
		case 483:
			return require('./assets/pokemon-assets/483.png')
		case 484:
			return require('./assets/pokemon-assets/484.png')
		case 485:
			return require('./assets/pokemon-assets/485.png')
		case 486:
			return require('./assets/pokemon-assets/486.png')
		case 487:
			return require('./assets/pokemon-assets/487.png')
		case 488:
			return require('./assets/pokemon-assets/488.png')
		case 489:
			return require('./assets/pokemon-assets/489.png')
		case 490:
			return require('./assets/pokemon-assets/490.png')
		case 491:
			return require('./assets/pokemon-assets/491.png')
		case 492:
			return require('./assets/pokemon-assets/492.png')
		case 493:
			return require('./assets/pokemon-assets/493.png')
		case 494:
			return require('./assets/pokemon-assets/494.png')
		case 495:
			return require('./assets/pokemon-assets/495.png')
		case 496:
			return require('./assets/pokemon-assets/496.png')
		case 497:
			return require('./assets/pokemon-assets/497.png')
		case 498:
			return require('./assets/pokemon-assets/498.png')
		case 499:
			return require('./assets/pokemon-assets/499.png')
		case 500:
			return require('./assets/pokemon-assets/500.png')
		case 501:
			return require('./assets/pokemon-assets/501.png')
		case 502:
			return require('./assets/pokemon-assets/502.png')
		case 503:
			return require('./assets/pokemon-assets/503.png')
		case 504:
			return require('./assets/pokemon-assets/504.png')
		case 505:
			return require('./assets/pokemon-assets/505.png')
		case 506:
			return require('./assets/pokemon-assets/506.png')
		case 507:
			return require('./assets/pokemon-assets/507.png')
		case 508:
			return require('./assets/pokemon-assets/508.png')
		case 509:
			return require('./assets/pokemon-assets/509.png')
		case 510:
			return require('./assets/pokemon-assets/510.png')
		case 511:
			return require('./assets/pokemon-assets/511.png')
		case 512:
			return require('./assets/pokemon-assets/512.png')
		case 513:
			return require('./assets/pokemon-assets/513.png')
		case 514:
			return require('./assets/pokemon-assets/514.png')
		case 515:
			return require('./assets/pokemon-assets/515.png')
		case 516:
			return require('./assets/pokemon-assets/516.png')
		case 517:
			return require('./assets/pokemon-assets/517.png')
		case 518:
			return require('./assets/pokemon-assets/518.png')
		case 519:
			return require('./assets/pokemon-assets/519.png')
		case 520:
			return require('./assets/pokemon-assets/520.png')
		case 521:
			return require('./assets/pokemon-assets/521.png')
		case 522:
			return require('./assets/pokemon-assets/522.png')
		case 523:
			return require('./assets/pokemon-assets/523.png')
		case 524:
			return require('./assets/pokemon-assets/524.png')
		case 525:
			return require('./assets/pokemon-assets/525.png')
		case 526:
			return require('./assets/pokemon-assets/526.png')
		case 527:
			return require('./assets/pokemon-assets/527.png')
		case 528:
			return require('./assets/pokemon-assets/528.png')
		case 529:
			return require('./assets/pokemon-assets/529.png')
		case 530:
			return require('./assets/pokemon-assets/530.png')
		case 531:
			return require('./assets/pokemon-assets/531.png')
		case 532:
			return require('./assets/pokemon-assets/532.png')
		case 533:
			return require('./assets/pokemon-assets/533.png')
		case 534:
			return require('./assets/pokemon-assets/534.png')
		case 535:
			return require('./assets/pokemon-assets/535.png')
		case 536:
			return require('./assets/pokemon-assets/536.png')
		case 537:
			return require('./assets/pokemon-assets/537.png')
		case 538:
			return require('./assets/pokemon-assets/538.png')
		case 539:
			return require('./assets/pokemon-assets/539.png')
		case 540:
			return require('./assets/pokemon-assets/540.png')
		case 541:
			return require('./assets/pokemon-assets/541.png')
		case 542:
			return require('./assets/pokemon-assets/542.png')
		case 543:
			return require('./assets/pokemon-assets/543.png')
		case 544:
			return require('./assets/pokemon-assets/544.png')
		case 545:
			return require('./assets/pokemon-assets/545.png')
		case 546:
			return require('./assets/pokemon-assets/546.png')
		case 547:
			return require('./assets/pokemon-assets/547.png')
		case 548:
			return require('./assets/pokemon-assets/548.png')
		case 549:
			return require('./assets/pokemon-assets/549.png')
		case 550:
			return require('./assets/pokemon-assets/550.png')
		case 551:
			return require('./assets/pokemon-assets/551.png')
		case 552:
			return require('./assets/pokemon-assets/552.png')
		case 553:
			return require('./assets/pokemon-assets/553.png')
		case 554:
			return require('./assets/pokemon-assets/554.png')
		case 555:
			return require('./assets/pokemon-assets/555.png')
		case 556:
			return require('./assets/pokemon-assets/556.png')
		case 557:
			return require('./assets/pokemon-assets/557.png')
		case 558:
			return require('./assets/pokemon-assets/558.png')
		case 559:
			return require('./assets/pokemon-assets/559.png')
		case 560:
			return require('./assets/pokemon-assets/560.png')
		case 561:
			return require('./assets/pokemon-assets/561.png')
		case 562:
			return require('./assets/pokemon-assets/562.png')
		case 563:
			return require('./assets/pokemon-assets/563.png')
		case 564:
			return require('./assets/pokemon-assets/564.png')
		case 565:
			return require('./assets/pokemon-assets/565.png')
		case 566:
			return require('./assets/pokemon-assets/566.png')
		case 567:
			return require('./assets/pokemon-assets/567.png')
		case 568:
			return require('./assets/pokemon-assets/568.png')
		case 569:
			return require('./assets/pokemon-assets/569.png')
		case 570:
			return require('./assets/pokemon-assets/570.png')
		case 571:
			return require('./assets/pokemon-assets/571.png')
		case 572:
			return require('./assets/pokemon-assets/572.png')
		case 573:
			return require('./assets/pokemon-assets/573.png')
		case 574:
			return require('./assets/pokemon-assets/574.png')
		case 575:
			return require('./assets/pokemon-assets/575.png')
		case 576:
			return require('./assets/pokemon-assets/576.png')
		case 577:
			return require('./assets/pokemon-assets/577.png')
		case 578:
			return require('./assets/pokemon-assets/578.png')
		case 579:
			return require('./assets/pokemon-assets/579.png')
		case 580:
			return require('./assets/pokemon-assets/580.png')
		case 581:
			return require('./assets/pokemon-assets/581.png')
		case 582:
			return require('./assets/pokemon-assets/582.png')
		case 583:
			return require('./assets/pokemon-assets/583.png')
		case 584:
			return require('./assets/pokemon-assets/584.png')
		case 585:
			return require('./assets/pokemon-assets/585.png')
		case 586:
			return require('./assets/pokemon-assets/586.png')
		case 587:
			return require('./assets/pokemon-assets/587.png')
		case 588:
			return require('./assets/pokemon-assets/588.png')
		case 589:
			return require('./assets/pokemon-assets/589.png')
		case 590:
			return require('./assets/pokemon-assets/590.png')
		case 591:
			return require('./assets/pokemon-assets/591.png')
		case 592:
			return require('./assets/pokemon-assets/592.png')
		case 593:
			return require('./assets/pokemon-assets/593.png')
		case 594:
			return require('./assets/pokemon-assets/594.png')
		case 595:
			return require('./assets/pokemon-assets/595.png')
		case 596:
			return require('./assets/pokemon-assets/596.png')
		case 597:
			return require('./assets/pokemon-assets/597.png')
		case 598:
			return require('./assets/pokemon-assets/598.png')
		case 599:
			return require('./assets/pokemon-assets/599.png')
		case 600:
			return require('./assets/pokemon-assets/600.png')
		case 601:
			return require('./assets/pokemon-assets/601.png')
		case 602:
			return require('./assets/pokemon-assets/602.png')
		case 603:
			return require('./assets/pokemon-assets/603.png')
		case 604:
			return require('./assets/pokemon-assets/604.png')
		case 605:
			return require('./assets/pokemon-assets/605.png')
		case 606:
			return require('./assets/pokemon-assets/606.png')
		case 607:
			return require('./assets/pokemon-assets/607.png')
		case 608:
			return require('./assets/pokemon-assets/608.png')
		case 609:
			return require('./assets/pokemon-assets/609.png')
		case 610:
			return require('./assets/pokemon-assets/610.png')
		case 611:
			return require('./assets/pokemon-assets/611.png')
		case 612:
			return require('./assets/pokemon-assets/612.png')
		case 613:
			return require('./assets/pokemon-assets/613.png')
		case 614:
			return require('./assets/pokemon-assets/614.png')
		case 615:
			return require('./assets/pokemon-assets/615.png')
		case 616:
			return require('./assets/pokemon-assets/616.png')
		case 617:
			return require('./assets/pokemon-assets/617.png')
		case 618:
			return require('./assets/pokemon-assets/618.png')
		case 619:
			return require('./assets/pokemon-assets/619.png')
		case 620:
			return require('./assets/pokemon-assets/620.png')
		case 621:
			return require('./assets/pokemon-assets/621.png')
		case 622:
			return require('./assets/pokemon-assets/622.png')
		case 623:
			return require('./assets/pokemon-assets/623.png')
		case 624:
			return require('./assets/pokemon-assets/624.png')
		case 625:
			return require('./assets/pokemon-assets/625.png')
		case 626:
			return require('./assets/pokemon-assets/626.png')
		case 627:
			return require('./assets/pokemon-assets/627.png')
		case 628:
			return require('./assets/pokemon-assets/628.png')
		case 629:
			return require('./assets/pokemon-assets/629.png')
		case 630:
			return require('./assets/pokemon-assets/630.png')
		case 631:
			return require('./assets/pokemon-assets/631.png')
		case 632:
			return require('./assets/pokemon-assets/632.png')
		case 633:
			return require('./assets/pokemon-assets/633.png')
		case 634:
			return require('./assets/pokemon-assets/634.png')
		case 635:
			return require('./assets/pokemon-assets/635.png')
		case 636:
			return require('./assets/pokemon-assets/636.png')
		case 637:
			return require('./assets/pokemon-assets/637.png')
		case 638:
			return require('./assets/pokemon-assets/638.png')
		case 639:
			return require('./assets/pokemon-assets/639.png')
		case 640:
			return require('./assets/pokemon-assets/640.png')
		case 641:
			return require('./assets/pokemon-assets/641.png')
		case 642:
			return require('./assets/pokemon-assets/642.png')
		case 643:
			return require('./assets/pokemon-assets/643.png')
		case 644:
			return require('./assets/pokemon-assets/644.png')
		case 645:
			return require('./assets/pokemon-assets/645.png')
		case 646:
			return require('./assets/pokemon-assets/646.png')
		case 647:
			return require('./assets/pokemon-assets/647.png')
		case 648:
			return require('./assets/pokemon-assets/648.png')
		case 649:
			return require('./assets/pokemon-assets/649.png')
		case 650:
			return require('./assets/pokemon-assets/650.png')
		case 651:
			return require('./assets/pokemon-assets/651.png')
		case 652:
			return require('./assets/pokemon-assets/652.png')
		case 653:
			return require('./assets/pokemon-assets/653.png')
		case 654:
			return require('./assets/pokemon-assets/654.png')
		case 655:
			return require('./assets/pokemon-assets/655.png')
		case 656:
			return require('./assets/pokemon-assets/656.png')
		case 657:
			return require('./assets/pokemon-assets/657.png')
		case 658:
			return require('./assets/pokemon-assets/658.png')
		case 659:
			return require('./assets/pokemon-assets/659.png')
		case 660:
			return require('./assets/pokemon-assets/660.png')
		case 661:
			return require('./assets/pokemon-assets/661.png')
		case 662:
			return require('./assets/pokemon-assets/662.png')
		case 663:
			return require('./assets/pokemon-assets/663.png')
		case 664:
			return require('./assets/pokemon-assets/664.png')
		case 665:
			return require('./assets/pokemon-assets/665.png')
		case 666:
			return require('./assets/pokemon-assets/666.png')
		case 667:
			return require('./assets/pokemon-assets/667.png')
		case 668:
			return require('./assets/pokemon-assets/668.png')
		case 669:
			return require('./assets/pokemon-assets/669.png')
		case 670:
			return require('./assets/pokemon-assets/670.png')
		case 671:
			return require('./assets/pokemon-assets/671.png')
		case 672:
			return require('./assets/pokemon-assets/672.png')
		case 673:
			return require('./assets/pokemon-assets/673.png')
		case 674:
			return require('./assets/pokemon-assets/674.png')
		case 675:
			return require('./assets/pokemon-assets/675.png')
		case 676:
			return require('./assets/pokemon-assets/676.png')
		case 677:
			return require('./assets/pokemon-assets/677.png')
		case 678:
			return require('./assets/pokemon-assets/678.png')
		case 679:
			return require('./assets/pokemon-assets/679.png')
		case 680:
			return require('./assets/pokemon-assets/680.png')
		case 681:
			return require('./assets/pokemon-assets/681.png')
		case 682:
			return require('./assets/pokemon-assets/682.png')
		case 683:
			return require('./assets/pokemon-assets/683.png')
		case 684:
			return require('./assets/pokemon-assets/684.png')
		case 685:
			return require('./assets/pokemon-assets/685.png')
		case 686:
			return require('./assets/pokemon-assets/686.png')
		case 687:
			return require('./assets/pokemon-assets/687.png')
		case 688:
			return require('./assets/pokemon-assets/688.png')
		case 689:
			return require('./assets/pokemon-assets/689.png')
		case 690:
			return require('./assets/pokemon-assets/690.png')
		case 691:
			return require('./assets/pokemon-assets/691.png')
		case 692:
			return require('./assets/pokemon-assets/692.png')
		case 693:
			return require('./assets/pokemon-assets/693.png')
		case 694:
			return require('./assets/pokemon-assets/694.png')
		case 695:
			return require('./assets/pokemon-assets/695.png')
		case 696:
			return require('./assets/pokemon-assets/696.png')
		case 697:
			return require('./assets/pokemon-assets/697.png')
		case 698:
			return require('./assets/pokemon-assets/698.png')
		case 699:
			return require('./assets/pokemon-assets/699.png')
		case 700:
			return require('./assets/pokemon-assets/700.png')
		case 701:
			return require('./assets/pokemon-assets/701.png')
		case 702:
			return require('./assets/pokemon-assets/702.png')
		case 703:
			return require('./assets/pokemon-assets/703.png')
		case 704:
			return require('./assets/pokemon-assets/704.png')
		case 705:
			return require('./assets/pokemon-assets/705.png')
		case 706:
			return require('./assets/pokemon-assets/706.png')
		case 707:
			return require('./assets/pokemon-assets/707.png')
		case 708:
			return require('./assets/pokemon-assets/708.png')
		case 709:
			return require('./assets/pokemon-assets/709.png')
		case 710:
			return require('./assets/pokemon-assets/710.png')
		case 711:
			return require('./assets/pokemon-assets/711.png')
		case 712:
			return require('./assets/pokemon-assets/712.png')
		case 713:
			return require('./assets/pokemon-assets/713.png')
		case 714:
			return require('./assets/pokemon-assets/714.png')
		case 715:
			return require('./assets/pokemon-assets/715.png')
		case 716:
			return require('./assets/pokemon-assets/716.png')
		case 717:
			return require('./assets/pokemon-assets/717.png')
		case 718:
			return require('./assets/pokemon-assets/718.png')
		default:
			return null
	}
}